# SPDX-License-Identifier: LGPL-2.1-or-later
---
name: Make a Github release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: github.repository == 'systemd/systemd'
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');

            core.info(`Creating release for tag: ${tag}`);

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: tag,
              prerelease: tag.includes('-rc'),
              draft: context.repo.repo === 'systemd',
            });
